// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public class IdentityProviderGrpcClient: GrpcClient<global::Sso.V1.IdentityProvider.IdentityProviderClient>, IIdentityProvider 
    {
        public IdentityProviderGrpcClient(string hostname, string scope, bool secure, float defaultTimeout = 10000): base(hostname, scope, secure, defaultTimeout)
        {
        }

        public global::Sso.V1.GetEntryURLResponse GetEntryURL(global::Sso.V1.GetEntryURLRequest req, RequestOptions? options = null) {
            return DoRequest("GetEntryURL", req, options) as global::Sso.V1.GetEntryURLResponse;
        }

        public global::Sso.V1.GetEntryURLWithCodeResponse GetEntryURLWithCode(global::Sso.V1.GetEntryURLWithCodeRequest req, RequestOptions? options = null) {
            return DoRequest("GetEntryURLWithCode", req, options) as global::Sso.V1.GetEntryURLWithCodeResponse;
        }

        public Google.Protobuf.WellKnownTypes.Empty Logout(global::Sso.V1.LogoutRequest req, RequestOptions? options = null) {
            return DoRequest("Logout", req, options) as Google.Protobuf.WellKnownTypes.Empty;
        }
    }
}
