// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public interface IIdentityProvider
    {
        global::Sso.V1.GetEntryURLResponse GetEntryURL(global::Sso.V1.GetEntryURLRequest req, RequestOptions? options = null);
        global::Sso.V1.GetEntryURLWithCodeResponse GetEntryURLWithCode(global::Sso.V1.GetEntryURLWithCodeRequest req, RequestOptions? options = null);
        Google.Protobuf.WellKnownTypes.Empty Logout(global::Sso.V1.LogoutRequest req, RequestOptions? options = null);
    }
}
