// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public interface IServiceProviderAdmin
    {
        Google.Protobuf.WellKnownTypes.Empty CreateServiceProvider(global::Sso.V1.CreateServiceProviderRequest req, RequestOptions? options = null);
        global::Sso.V1.GetServiceProviderResponse GetServiceProvider(global::Sso.V1.GetServiceProviderRequest req, RequestOptions? options = null);
        Google.Protobuf.WellKnownTypes.Empty UpdateServiceProvider(global::Sso.V1.UpdateServiceProviderRequest req, RequestOptions? options = null);
        Google.Protobuf.WellKnownTypes.Empty DeleteServiceProvider(global::Sso.V1.DeleteServiceProviderRequest req, RequestOptions? options = null);
    }
}
