// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public interface IServiceProvider
    {
        global::Sso.V1.GetSessionTransferURLResponse GetSessionTransferURL(global::Sso.V1.GetSessionTransferURLRequest req, RequestOptions? options = null);
    }
}
