// Code generated by sdkgen
// Generated on 2018-08-09 19:42:47.7876276 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using System;
using Vendasta.Vax;
using Environment = Vendasta.Vax.Environment;

namespace Vendasta.SalesOrders
{
    public class SalesOrdersGeneratedClient: ISalesOrders 
    {
        private readonly ISalesOrders _transport;
        public SalesOrdersGeneratedClient(Environment env, float defaultTimeout)
        {
            _transport = GetTransportClient(env, defaultTimeout);
        }

        private static ISalesOrders GetTransportClient(Environment env, float defaultTimeout)
        {
            var config = GetEnvConfig(env);
            Console.Write(config.Secure);
            return new SalesOrdersGrpcClient(
                config.Host,
                config.Scope,
                config.Secure,
                defaultTimeout
            );
        }

        private static EnvironmentConfig GetEnvConfig(Environment env)
        {
            return Config.GetEnvironmentConfig(env);
        }

        public global::Salesorders.V1.CreateSalesOrderResponse CreateSalesOrder(global::Salesorders.V1.CreateSalesOrderRequest req, RequestOptions? options = null) {
            return _transport.CreateSalesOrder(req, options);
        }

        public global::Salesorders.V1.GetSalesOrderResponse GetSalesOrder(global::Salesorders.V1.GetSalesOrderRequest req, RequestOptions? options = null) {
            return _transport.GetSalesOrder(req, options);
        }

        public global::Salesorders.V1.ListSalesOrderResponse ListSalesOrder(global::Salesorders.V1.ListSalesOrderRequest req, RequestOptions? options = null) {
            return _transport.ListSalesOrder(req, options);
        }

        public global::Salesorders.V1.ApproveSalesOrderResponse ApproveSalesOrder(global::Salesorders.V1.ApproveSalesOrderRequest req, RequestOptions? options = null) {
            return _transport.ApproveSalesOrder(req, options);
        }

        public global::Salesorders.V1.DeclineSalesOrderResponse DeclineSalesOrder(global::Salesorders.V1.DeclineSalesOrderRequest req, RequestOptions? options = null) {
            return _transport.DeclineSalesOrder(req, options);
        }

        public global::Salesorders.V1.ActivateProductsResponse ActivateProducts(global::Salesorders.V1.ActivateProductsRequest req, RequestOptions? options = null) {
            return _transport.ActivateProducts(req, options);
        }
    }
}
