// Code generated by sdkgen
// Generated on 2018-08-09 19:42:47.7876276 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.SalesOrders
{
    public class SalesOrdersGrpcClient: GrpcClient<global::Salesorders.V1.SalesOrders.SalesOrdersClient>, ISalesOrders 
    {
        public SalesOrdersGrpcClient(string hostname, string scope, bool secure, float defaultTimeout = 10000): base(hostname, scope, secure, defaultTimeout)
        {
        }

        public global::Salesorders.V1.CreateSalesOrderResponse CreateSalesOrder(global::Salesorders.V1.CreateSalesOrderRequest req, RequestOptions? options = null) {
            return DoRequest("CreateSalesOrder", req, options) as global::Salesorders.V1.CreateSalesOrderResponse;
        }

        public global::Salesorders.V1.GetSalesOrderResponse GetSalesOrder(global::Salesorders.V1.GetSalesOrderRequest req, RequestOptions? options = null) {
            return DoRequest("GetSalesOrder", req, options) as global::Salesorders.V1.GetSalesOrderResponse;
        }

        public global::Salesorders.V1.ListSalesOrderResponse ListSalesOrder(global::Salesorders.V1.ListSalesOrderRequest req, RequestOptions? options = null) {
            return DoRequest("ListSalesOrder", req, options) as global::Salesorders.V1.ListSalesOrderResponse;
        }

        public global::Salesorders.V1.ApproveSalesOrderResponse ApproveSalesOrder(global::Salesorders.V1.ApproveSalesOrderRequest req, RequestOptions? options = null) {
            return DoRequest("ApproveSalesOrder", req, options) as global::Salesorders.V1.ApproveSalesOrderResponse;
        }

        public global::Salesorders.V1.DeclineSalesOrderResponse DeclineSalesOrder(global::Salesorders.V1.DeclineSalesOrderRequest req, RequestOptions? options = null) {
            return DoRequest("DeclineSalesOrder", req, options) as global::Salesorders.V1.DeclineSalesOrderResponse;
        }

        public global::Salesorders.V1.ActivateProductsResponse ActivateProducts(global::Salesorders.V1.ActivateProductsRequest req, RequestOptions? options = null) {
            return DoRequest("ActivateProducts", req, options) as global::Salesorders.V1.ActivateProductsResponse;
        }
    }
}
