// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public class ServiceProviderAdminGrpcClient: GrpcClient<global::Sso.V1.ServiceProviderAdmin.ServiceProviderAdminClient>, IServiceProviderAdmin 
    {
        public ServiceProviderAdminGrpcClient(string hostname, string scope, bool secure, float defaultTimeout = 10000): base(hostname, scope, secure, defaultTimeout)
        {
        }

        public Google.Protobuf.WellKnownTypes.Empty CreateServiceProvider(global::Sso.V1.CreateServiceProviderRequest req, RequestOptions? options = null) {
            return DoRequest("CreateServiceProvider", req, options) as Google.Protobuf.WellKnownTypes.Empty;
        }

        public global::Sso.V1.GetServiceProviderResponse GetServiceProvider(global::Sso.V1.GetServiceProviderRequest req, RequestOptions? options = null) {
            return DoRequest("GetServiceProvider", req, options) as global::Sso.V1.GetServiceProviderResponse;
        }

        public Google.Protobuf.WellKnownTypes.Empty UpdateServiceProvider(global::Sso.V1.UpdateServiceProviderRequest req, RequestOptions? options = null) {
            return DoRequest("UpdateServiceProvider", req, options) as Google.Protobuf.WellKnownTypes.Empty;
        }

        public Google.Protobuf.WellKnownTypes.Empty DeleteServiceProvider(global::Sso.V1.DeleteServiceProviderRequest req, RequestOptions? options = null) {
            return DoRequest("DeleteServiceProvider", req, options) as Google.Protobuf.WellKnownTypes.Empty;
        }
    }
}
