// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public class ServiceProviderGrpcClient: GrpcClient<global::Sso.V1.ServiceProvider.ServiceProviderClient>, IServiceProvider 
    {
        public ServiceProviderGrpcClient(string hostname, string scope, bool secure, float defaultTimeout = 10000): base(hostname, scope, secure, defaultTimeout)
        {
        }

        public global::Sso.V1.GetSessionTransferURLResponse GetSessionTransferURL(global::Sso.V1.GetSessionTransferURLRequest req, RequestOptions? options = null) {
            return DoRequest("GetSessionTransferURL", req, options) as global::Sso.V1.GetSessionTransferURLResponse;
        }
    }
}
