// Code generated by sdkgen
// Generated on 2018-08-03 14:36:42.9118512 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
// DO NOT EDIT!

using Vendasta.Vax;

namespace Vendasta.Sso
{
    public class ServiceProviderAdminGeneratedClient: IServiceProviderAdmin 
    {
        private readonly IServiceProviderAdmin _transport;
        public ServiceProviderAdminGeneratedClient(Environment env, float defaultTimeout)
        {
            _transport = GetTransportClient(env, defaultTimeout);
        }

        private static IServiceProviderAdmin GetTransportClient(Environment env, float defaultTimeout)
        {
            var config = GetEnvConfig(env);
            return new ServiceProviderAdminGrpcClient(
                config.Host,
                config.Scope,
                config.Secure,
                defaultTimeout
            );
        }

        private static EnvironmentConfig GetEnvConfig(Environment env)
        {
            return Config.GetEnvironmentConfig(env);
        }

        public Google.Protobuf.WellKnownTypes.Empty CreateServiceProvider(global::Sso.V1.CreateServiceProviderRequest req, RequestOptions? options = null) {
            return _transport.CreateServiceProvider(req, options);
        }

        public global::Sso.V1.GetServiceProviderResponse GetServiceProvider(global::Sso.V1.GetServiceProviderRequest req, RequestOptions? options = null) {
            return _transport.GetServiceProvider(req, options);
        }

        public Google.Protobuf.WellKnownTypes.Empty UpdateServiceProvider(global::Sso.V1.UpdateServiceProviderRequest req, RequestOptions? options = null) {
            return _transport.UpdateServiceProvider(req, options);
        }

        public Google.Protobuf.WellKnownTypes.Empty DeleteServiceProvider(global::Sso.V1.DeleteServiceProviderRequest req, RequestOptions? options = null) {
            return _transport.DeleteServiceProvider(req, options);
        }
    }
}
